namespace: ""
image:
  repository: public.ecr.aws/whatap/whatap-operator
  tag: latest
  pullPolicy: Always

# Image pull secret for private registries
imagePullSecret:
  name: # registryKey

# Pod scheduling and priority options for the operator
priorityClassName: ""
nodeName: ""
nodeSelector: {}
affinity: {}
tolerations: []

credentials:
  create: false
  # The secret name is fixed to 'whatap-credentials'
  license: "" # <license-key>
  host: ""    # <whatap-server-host>
  port: 6600   # <whatap-server-port>
env: