{{ if .Values.deploymentOpen.enabled }}
{{- if .Values.k8sOldVersion }}
apiVersion: extensions/v1beta1
{{- else }}
apiVersion: apps/v1
{{end}}
kind: Deployment
metadata:
  name: {{ .Values.deploymentOpen.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deploymentOpen.replicas }}
  {{- if not .Values.k8sOldVersion }}
  selector:
    matchLabels:
      name: {{ .Values.deploymentOpen.label }}
  {{end}}
  template:
    metadata:
      labels:
        name: {{ .Values.deploymentOpen.label }}
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      tolerations:
      {{- if .Values.deploymentOpen.tolerations}}
      {{ toYaml .Values.deploymentOpen.tolerations | nindent 8 }}
      {{- end }}
      affinity:
      {{- if .Values.deploymentOpen.affinity }}
      {{ toYaml .Values.deploymentOpen.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: whatap-open-agent-sa
      volumes:
        - name: config-volume
          configMap:
            name: whatap-open-agent-config
        - name: logs-volume
          emptyDir: {}
      containers:
        - name: {{ .Values.deploymentOpen.containers.openAgent.name }}
          {{- $secretName := default "whatap-credentials" .Values.whatap.existingSecretName }}
          image: {{ .Values.deploymentOpen.containers.openAgent.image }}
          imagePullPolicy: Always
          {{- if .Values.deploymentOpen.containers.openAgent.resources }}
          resources:
            {{- if .Values.deploymentOpen.containers.openAgent.resources.requests }}
            requests:
              {{- if .Values.deploymentOpen.containers.openAgent.resources.requests.memory }}
              memory: {{ .Values.deploymentOpen.containers.openAgent.resources.requests.memory }}
              {{- end }}
              {{- if .Values.deploymentOpen.containers.openAgent.resources.requests.cpu }}
              cpu: {{ .Values.deploymentOpen.containers.openAgent.resources.requests.cpu }}
              {{- end }}
            {{- end }}
            {{- if .Values.deploymentOpen.containers.openAgent.resources.limits }}
            limits:
              {{- if .Values.deploymentOpen.containers.openAgent.resources.limits.memory }}
              memory: {{ .Values.deploymentOpen.containers.openAgent.resources.limits.memory }}
              {{- end }}
              {{- if .Values.deploymentOpen.containers.openAgent.resources.limits.cpu }}
              cpu: {{ .Values.deploymentOpen.containers.openAgent.resources.limits.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
          env:
            - name: WHATAP_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: WHATAP_LICENSE
            - name: WHATAP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: WHATAP_HOST
            - name: WHATAP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: WHATAP_PORT
            {{- if .Values.deploymentOpen.containers.openAgent.envs }}
            {{- range $key, $value := .Values.deploymentOpen.containers.openAgent.envs }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/scrape_config.yaml
              subPath: scrape_config.yaml
            - name: logs-volume
              mountPath: /app/logs
{{ end }}
