{{- $createSecret := .Values.whatap.createSecret }}
{{- if eq $createSecret nil }}
{{- $createSecret = true }}
{{- end }}
{{- $secretName := default "whatap-credentials" .Values.whatap.existingSecretName }}
{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  WHATAP_LICENSE: {{ .Values.whatap.license | b64enc }}
  WHATAP_HOST: {{ .Values.whatap.host | b64enc }}
  WHATAP_PORT: {{ .Values.whatap.port | toString | b64enc }}
{{- end }}